server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
    # aggregation 为单体聚合部署模式；dev 使用 gateway + admin + project 独立服务模式
    active: dev
    # active: aggregation
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
